# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fir_fpga/fir_fpga.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_fpga || ORIG_REF_NAME==fir_fpga} -quiet] -quiet

# IP: bd/fir_fpga/ip/fir_fpga_processing_system7_0_0/fir_fpga_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_fpga_processing_system7_0_0 || ORIG_REF_NAME==fir_fpga_processing_system7_0_0} -quiet] -quiet

# IP: bd/fir_fpga/ip/fir_fpga_fir_0_0/fir_fpga_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_fpga_fir_0_0 || ORIG_REF_NAME==fir_fpga_fir_0_0} -quiet] -quiet

# IP: bd/fir_fpga/ip/fir_fpga_ps7_0_axi_periph_0/fir_fpga_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_fpga_ps7_0_axi_periph_0 || ORIG_REF_NAME==fir_fpga_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/fir_fpga/ip/fir_fpga_rst_ps7_0_100M_0/fir_fpga_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_fpga_rst_ps7_0_100M_0 || ORIG_REF_NAME==fir_fpga_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/fir_fpga/ip/fir_fpga_auto_pc_0/fir_fpga_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_fpga_auto_pc_0 || ORIG_REF_NAME==fir_fpga_auto_pc_0} -quiet] -quiet

# XDC: /home/user/vlsi/vivado/exer5/exer5.gen/sources_1/bd/fir_fpga/fir_fpga_ooc.xdc
