# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/demo2/demo2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2 || ORIG_REF_NAME==demo2} -quiet] -quiet

# IP: bd/demo2/ip/demo2_processing_system7_0_0/demo2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_processing_system7_0_0 || ORIG_REF_NAME==demo2_processing_system7_0_0} -quiet] -quiet

# IP: bd/demo2/ip/demo2_axi_gpio_0_1/demo2_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_axi_gpio_0_1 || ORIG_REF_NAME==demo2_axi_gpio_0_1} -quiet] -quiet

# IP: bd/demo2/ip/demo2_axi_gpio_1_0/demo2_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_axi_gpio_1_0 || ORIG_REF_NAME==demo2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/demo2/ip/demo2_xbar_0/demo2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_xbar_0 || ORIG_REF_NAME==demo2_xbar_0} -quiet] -quiet

# IP: bd/demo2/ip/demo2_auto_pc_0/demo2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_auto_pc_0 || ORIG_REF_NAME==demo2_auto_pc_0} -quiet] -quiet

# IP: bd/demo2/ip/demo2_ps7_0_axi_periph_0/demo2_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_ps7_0_axi_periph_0 || ORIG_REF_NAME==demo2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/demo2/ip/demo2_rst_ps7_0_100M_0/demo2_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo2_rst_ps7_0_100M_0 || ORIG_REF_NAME==demo2_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /home/user/vlsi/zybodemo/zybodemo.gen/sources_1/bd/demo2/demo2_ooc.xdc
