# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/vlsi3/vivado/best_fir/best_fir.srcs/sources_1/bd/best_fir/ip/best_fir_rst_ps7_0_100M_0/best_fir_rst_ps7_0_100M_0.xci
# IP: The module: 'best_fir_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vlsi3/vivado/best_fir/best_fir.gen/sources_1/bd/best_fir/ip/best_fir_rst_ps7_0_100M_0/best_fir_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'best_fir_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/vlsi3/vivado/best_fir/best_fir.gen/sources_1/bd/best_fir/ip/best_fir_rst_ps7_0_100M_0/best_fir_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'best_fir_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/vlsi3/vivado/best_fir/best_fir.gen/sources_1/bd/best_fir/ip/best_fir_rst_ps7_0_100M_0/best_fir_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'best_fir_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/vlsi3/vivado/best_fir/best_fir.srcs/sources_1/bd/best_fir/ip/best_fir_rst_ps7_0_100M_0/best_fir_rst_ps7_0_100M_0.xci
# IP: The module: 'best_fir_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vlsi3/vivado/best_fir/best_fir.gen/sources_1/bd/best_fir/ip/best_fir_rst_ps7_0_100M_0/best_fir_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'best_fir_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/vlsi3/vivado/best_fir/best_fir.gen/sources_1/bd/best_fir/ip/best_fir_rst_ps7_0_100M_0/best_fir_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'best_fir_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/vlsi3/vivado/best_fir/best_fir.gen/sources_1/bd/best_fir/ip/best_fir_rst_ps7_0_100M_0/best_fir_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'best_fir_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
