# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/final_fir/final_fir.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_fir || ORIG_REF_NAME==final_fir} -quiet] -quiet

# IP: bd/final_fir/ip/final_fir_processing_system7_0_0/final_fir_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_fir_processing_system7_0_0 || ORIG_REF_NAME==final_fir_processing_system7_0_0} -quiet] -quiet

# IP: bd/final_fir/ip/final_fir_best_fir_0_0/final_fir_best_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_fir_best_fir_0_0 || ORIG_REF_NAME==final_fir_best_fir_0_0} -quiet] -quiet

# IP: bd/final_fir/ip/final_fir_auto_pc_0/final_fir_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_fir_auto_pc_0 || ORIG_REF_NAME==final_fir_auto_pc_0} -quiet] -quiet

# IP: bd/final_fir/ip/final_fir_ps7_0_axi_periph_0/final_fir_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_fir_ps7_0_axi_periph_0 || ORIG_REF_NAME==final_fir_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/final_fir/ip/final_fir_rst_ps7_0_100M_0/final_fir_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_fir_rst_ps7_0_100M_0 || ORIG_REF_NAME==final_fir_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/vlsi3/vivado/final/final.gen/sources_1/bd/final_fir/final_fir_ooc.xdc
