#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Apr 10 09:11:11 +0000 2025
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim fir_tb_func_impl -key {Post-Implementation:sim_1:Functional:fir_tb} -tclbatch fir_tb.tcl -protoinst "protoinst_files/fir_fpga.protoinst" -log simulate.log"
xsim fir_tb_func_impl -key {Post-Implementation:sim_1:Functional:fir_tb} -tclbatch fir_tb.tcl -protoinst "protoinst_files/fir_fpga.protoinst" -log simulate.log

