# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/vlsi3/vivado/final/final.srcs/sources_1/bd/final_fir/ip/final_fir_auto_pc_0/final_fir_auto_pc_0.xci
# IP: The module: 'final_fir_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vlsi3/vivado/final/final.gen/sources_1/bd/final_fir/ip/final_fir_auto_pc_0/final_fir_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'final_fir_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/vlsi3/vivado/final/final.srcs/sources_1/bd/final_fir/ip/final_fir_auto_pc_0/final_fir_auto_pc_0.xci
# IP: The module: 'final_fir_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vlsi3/vivado/final/final.gen/sources_1/bd/final_fir/ip/final_fir_auto_pc_0/final_fir_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'final_fir_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
