# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/vlsi/zybodemo/zybodemo.srcs/sources_1/bd/demo2/ip/demo2_processing_system7_0_0/demo2_processing_system7_0_0.xci
# IP: The module: 'demo2_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/vlsi/zybodemo/zybodemo.gen/sources_1/bd/demo2/ip/demo2_processing_system7_0_0/demo2_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo2_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user/vlsi/zybodemo/zybodemo.srcs/sources_1/bd/demo2/ip/demo2_processing_system7_0_0/demo2_processing_system7_0_0.xci
# IP: The module: 'demo2_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/vlsi/zybodemo/zybodemo.gen/sources_1/bd/demo2/ip/demo2_processing_system7_0_0/demo2_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo2_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
